/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      fontFamily: {
        okra: ['Okra-Regular', 'Okra-Medium', 'Okra-ExtraBold', 'Okra-Bold', 'Okra-MediumLight'],
      },
      colors: {
        background: 'var(--color-background)',
        foreground: 'var(--color-foreground)',
        card: 'var(--color-card)',
        cardForeground: 'var(--color-cardForeground)',
        popover: 'var(--color-popover)',
        popoverForeground: 'var(--color-popoverForeground)',
        primary: 'var(--color-primary)',
        primaryForeground: 'var(--color-primaryForeground)',
        secondary: 'var(--color-secondary)',
        secondaryForeground: 'var(--color-secondaryForeground)',
        muted: 'var(--color-muted)',
        mutedForeground: 'var(--color-mutedForeground)',
        accent: 'var(--color-accent)',
        accentForeground: 'var(--color-accentForeground)',
        destructive: 'var(--color-destructive)',
        destructiveForeground: 'var(--color-destructiveForeground)',
        border: 'var(--color-border)',
        input: 'var(--color-input)',
        ring: 'var(--color-ring)',
        radius: 'var(--color-radius)',
        chart1: 'var(--color-chart1)',
        chart2: 'var(--color-chart2)',
        chart3: 'var(--color-chart3)',
        chart4: 'var(--color-chart4)',
        chart5: 'var(--color-chart5)',
        sidebar: 'var(--color-sidebar)',
        sidebarForeground: 'var(--color-sidebarForeground)',
        sidebarPrimary: 'var(--color-sidebarPrimary)',
        sidebarPrimaryForeground: 'var(--color-sidebarPrimaryForeground)',
        sidebarAccent: 'var(--color-sidebarAccent)',
        sidebarAccentForeground: 'var(--color-sidebarAccentForeground)',
        sidebarBorder: 'var(--color-sidebarBorder)',
        sidebarRing: 'var(--color-sidebarRing)',
      },
    },
  },
  future: {
    hoverOnlyWhenSupported: true,
  },
  plugins: [require('tailwindcss-animate')],
};
