export default {
  home: {
    headerTitle: 'হোম',
    newsSection: 'সর্বশেষ খবর',
    taxTypes: 'সেবা সমূহ',
    loading: 'কর এর ধরন লোড হচ্ছে...',
    error: 'কর ক্যাটাগরি লোড করতে ব্যর্থ হয়েছে',
    notFound: 'কোন কর ক্যাটাগরি পাওয়া যায়নি',
  },
  profile: {
    headerTitle: 'প্রোফাইল',
    headerDescription: 'আপনার অ্যাকাউন্ট এবং পছন্দগুলি পরিচালনা করুন',
    overview: 'সংক্ষিপ্ত বিবরণ',
    orders: 'অর্ডার',
    payments: 'পেমেন্ট',
    documents: 'ডকুমেন্টস',
    activity: 'কার্যকলাপ',
    paymentHistory: 'আপনার সমস্ত পেমেন্ট ইতিহাস দেখুন',
    taxOrders: 'আপনার সমস্ত ট্যাক্স অর্ডার দেখুন',
    uploadedFiles: 'আপনার আপলোড করা ফাইলগুলি পরিচালনা করুন',
    infoSupport: 'তথ্য এবং সহায়তা',
    aboutUs: 'আমাদের সম্পর্কে',
    aboutUsDesc: 'স্মার্ট ট্যাক্স বিডি সম্পর্কে আরও জানুন',
    contactUs: 'আমাদের সাথে যোগাযোগ করুন',
    contactUsDesc: 'আমাদের সাপোর্ট টিমের সাথে যোগাযোগ করুন',
    account: 'অ্যাকাউন্ট',
    signOut: 'সাইন আউট',
    signOutConfirm: 'আপনি কি নিশ্চিত যে আপনি সাইন আউট করতে চান?',
    deleteAccount: 'অ্যাকাউন্ট মুছে ফেলুন',
    deleteAccountDesc:
      'এই ক্রিয়াটি স্থায়ী এবং পূর্বাবস্থায় ফেরানো যাবে না। আপনার সমস্ত ডেটা সরানো হবে।',
    deleteConfirm: 'মুছে ফেলুন',
    notSignedIn: 'আপনি সাইন ইন করেননি',
    notSignedInDesc:
      'আপনার ডেটা সিঙ্ক করতে, ড্রাফ্ট সংরক্ষণ করতে এবং ট্যাক্স তথ্য পরিচালনা করতে সাইন ইন করুন।',
    signIn: 'সাইন ইন',
    createAccount: 'অ্যাকাউন্ট তৈরি করুন',
    role: 'ভূমিকা',
    location: 'অবস্থান',
    locationNA: 'পাওয়া যায় না',
  },
  common: {
    back_to_payment: 'পেমেন্টে ফিরে যান',
    yes: 'হ্যাঁ',
    no: 'না',
    cancel: 'বাতিল',
    see_all: 'সব দেখুন',
    view_all: 'সব দেখুন',
    not_available: 'প্রযোজ্য নয়',
    note: 'নোট:',
    featured: 'ফিচারড',
    from: 'থেকে:',
    subtotal: 'সাবটোটাল',
    shipping: 'শিপিং',
    tax: 'ট্যাক্স',
    total: 'মোট',
    free: 'ফ্রি',
    change: 'পরিবর্তন করুন',
    add: 'যোগ করুন',
    done: 'সম্পন্ন',
    loading: 'অপেক্ষা করুন...',
  },
};
