export default {
  home: {
    headerTitle: 'হোম',
    newsSection: 'সর্বশেষ খবর',
    taxTypes: 'সেবা সমূহ',
    loading: 'কর এর ধরন লোড হচ্ছে...',
    error: 'কর ক্যাটাগরি লোড করতে ব্যর্থ হয়েছে',
    notFound: 'কোন কর ক্যাটাগরি পাওয়া যায়নি',
    news: 'খবর',
    loadingNews: 'খবর লোড হচ্ছে...',
  },
  profile: {
    headerTitle: 'প্রোফাইল',
    headerDescription: 'আপনার অ্যাকাউন্ট এবং পছন্দগুলি পরিচালনা করুন',
    overview: 'সংক্ষিপ্ত বিবরণ',
    orders: 'অর্ডার',
    payments: 'পেমেন্ট',
    documents: 'ডকুমেন্টস',
    activity: 'কার্যকলাপ',
    paymentHistory: 'আপনার সমস্ত পেমেন্ট ইতিহাস দেখুন',
    taxOrders: 'আপনার সমস্ত ট্যাক্স অর্ডার দেখুন',
    uploadedFiles: 'আপনার আপলোড করা ফাইলগুলি পরিচালনা করুন',
    infoSupport: 'তথ্য এবং সহায়তা',
    aboutUs: 'আমাদের সম্পর্কে',
    aboutUsDesc: 'স্মার্ট ট্যাক্স বিডি সম্পর্কে আরও জানুন',
    contactUs: 'আমাদের সাথে যোগাযোগ করুন',
    contactUsDesc: 'আমাদের সাপোর্ট টিমের সাথে যোগাযোগ করুন',
    account: 'অ্যাকাউন্ট',
    signOut: 'সাইন আউট',
    signOutConfirm: 'আপনি কি নিশ্চিত যে আপনি সাইন আউট করতে চান?',
    deleteAccount: 'অ্যাকাউন্ট মুছে ফেলুন',
    deleteAccountDesc:
      'এই ক্রিয়াটি স্থায়ী এবং পূর্বাবস্থায় ফেরানো যাবে না। আপনার সমস্ত ডেটা সরানো হবে।',
    deleteConfirm: 'মুছে ফেলুন',
    notSignedIn: 'আপনি সাইন ইন করেননি',
    notSignedInDesc:
      'আপনার ডেটা সিঙ্ক করতে, ড্রাফ্ট সংরক্ষণ করতে এবং ট্যাক্স তথ্য পরিচালনা করতে সাইন ইন করুন।',
    signIn: 'সাইন ইন',
    createAccount: 'অ্যাকাউন্ট তৈরি করুন',
    role: 'ভূমিকা',
    location: 'অবস্থান',
    locationNA: 'পাওয়া যায় না',
  },
  common: {
    back_to_payment: 'পেমেন্টে ফিরে যান',
    yes: 'হ্যাঁ',
    no: 'না',
    cancel: 'বাতিল',
    see_all: 'সব দেখুন',
    view_all: 'সব দেখুন',
    not_available: 'প্রযোজ্য নয়',
    note: 'নোট:',
    featured: 'ফিচারড',
    from: 'থেকে:',
    subtotal: 'সাবটোটাল',
    shipping: 'শিপিং',
    tax: 'ট্যাক্স',
    total: 'মোট',
    free: 'ফ্রি',
    change: 'পরিবর্তন করুন',
    add: 'যোগ করুন',
    done: 'সম্পন্ন',
    loading: 'অপেক্ষা করুন...',
    noDataTitle: 'কোন তথ্য পাওয়া যায়নি',
    noDataMessage: 'পরে আবার চেষ্টা করুন অথবা আপনার ফিল্টারগুলি পরিবর্তন করুন।',
    docDefault: 'ডকুমেন্ট',
    fileUploaded: 'ফাইল আপলোড করা হয়েছে',
    noFileYet: 'এখনো কোনো ফাইল নেই',
    tapToReplace: 'পরিবর্তন করতে ট্যাপ করুন',
    tapToUpload: 'আপলোড করতে ট্যাপ করুন',
    view: 'দেখুন',
    missing: 'মিসিং',
    preview: 'প্রিভিউ',
    previewImage: 'নিচে ছবির প্রিভিউ দেখুন',
    previewPdf: 'পিডিএফ ডকুমেন্ট',
    previewOther: 'এই ফাইলটি দেখতে ডাউনলোড করুন',
    pdfNotSupported: 'অ্যাপের ভেতরে পিডিএফ প্রিভিউ সমর্থিত নয়।',
    openPdfBrowser: 'ব্রাউজারে পিডিএফ খুলুন',
    previewNotAvailable: 'প্রিভিউ উপলব্ধ নেই।\nদেখতে ডাউনলোড করুন।',
    close: 'বন্ধ করুন',
    download: 'ডাউনলোড',
    downloading: 'ডাউনলোড হচ্ছে...',
    popular: 'জনপ্রিয়',
    recommended: 'সুপারিশকৃত',
    contactForPricing: 'মূল্যের জন্য যোগাযোগ করুন',
    showFeatures: 'ফিচারগুলো দেখুন',
    hideFeatures: 'ফিচারগুলো লুকান',
    tabHome: 'হোম',
    tabNews: 'নিউজ',
    tabFaq: 'এফএকিউ',
    tabProfile: 'প্রোফাইল',
  },
  auth: {
    signInTitle: 'সাইন ইন',
    signUpTitle: 'অ্যাকাউন্ট তৈরি করুন',
    forgotPasswordTitle: 'পাসওয়ার্ড ভুলে গেছেন?',
    verifyOtpTitle: 'ওটিপি যাচাই করুন',
    mobilePlaceholder: 'আপনার মোবাইল নম্বর লিখুন...',
    passwordPlaceholder: 'পাসওয়ার্ড *',
    fullNamePlaceholder: 'পুরো নাম *',
    emailPlaceholder: 'ইমেল ঠিকানা',
    confirmPasswordPlaceholder: 'পাসওয়ার্ড নিশ্চিত করুন *',
    rememberMe: 'মনে রাখুন',
    forgotPasswordLink: 'পাসওয়ার্ড ভুলে গেছেন?',
    signInButton: 'লগ ইন',
    signingIn: 'সাইন ইন হচ্ছে...',
    signUpLink: 'স্মার্ট ট্যাক্স বিডিতে নতুন?',
    signUpLinkAction: 'অ্যাকাউন্ট তৈরি করুন',
    termsAndConditions: 'আমি সেবার শর্তাবলী এবং গোপনীয়তা নীতিতে সম্মত',
    createAccountButton: 'অ্যাকাউন্ট তৈরি করুন',
    softwareSlogan: 'বাংলাদেশের এক নম্বর ট্যাক্স সফটওয়্যার',
    createAccountSlogan: 'আসুন আপনার স্মার্ট ট্যাক্স বিডি অ্যাকাউন্ট তৈরি করি',
    madeIn: 'তৈরি',
    copyright:
      'মোবাইল অ্যাপটি স্মার্ট ট্যাক্স বিডি টেকনোলজি লিমিটেড দ্বারা তৈরি। smarttaxbd.com.bd বাংলাদেশ কপিরাইট এবং পেটেন্ট অফিস দ্বারা কপিরাইট করা। কপিরাইট রেজিস্ট্রেশন নম্বর ১৪৭৪৮-সিওপিআর।',
    forgotPasswordDesc:
      'আপনার মোবাইল নম্বর লিখুন এবং আমরা আপনার পাসওয়ার্ড রিসেট করার জন্য একটি ওটিপি পাঠাব।',
    mobileLabel: 'মোবাইল নম্বর',
    sendOtpButton: 'ওটিপি পাঠান',
    rememberPassword: 'পাসওয়ার্ড মনে আছে?',
    verifyOtpDesc: 'আমরা একটি ৬-ডিজিটের যাচাইকরণ কোড পাঠিয়েছি',
    mobileNumberDefault: 'আপনার মোবাইল নম্বরে',
    resendCodeIn: 'কোড পুনরায় পাঠাব',
    didNotReceiveCode: 'কোড পাননি?',
    resend: 'পুনরায় পাঠান',
    verifyOtpButton: 'ওটিপি যাচাই করুন',
    verifyOtpHelp: 'চালিয়ে যেতে আপনার মোবাইল নম্বরে পাঠানো ৬-ডিজিটের কোডটি লিখুন।',
    nameMin: 'নাম অন্তত ২ অক্ষরের হতে হবে',
    emailRequired: 'ইমেল প্রয়োজন',
    emailInvalid: 'সঠিক ইমেল ঠিকানা লিখুন',
    mobileMin: 'ফোন নম্বর অন্তত ১১ অক্ষরের হতে হবে',
    passwordMin: 'পাসওয়ার্ড অন্তত ৬ অক্ষরের হতে হবে',
    termsRequired: 'আপনাকে শর্তাবলী গ্রহণ করতে হবে',
    passwordsMismatch: 'পাসওয়ার্ড মিলছে না',
  },
};
