export default {
  home: {
    headerTitle: 'Home',
    newsSection: 'Latest News',
    taxTypes: 'Services',
    taxCategories: 'Tax Categories',
    taxCategoriesSubtitle: 'Choose the category that matches your income',
    loading: 'Loading tax types...',
    error: 'Failed to load tax categories',
    notFound: 'No tax categories found',
    news: 'News',
    loadingNews: 'Loading news...',
  },
  profile: {
    headerTitle: 'Profile',
    headerDescription: 'Manage your account and preferences',
    overview: 'Overview',
    orders: 'Orders',
    payments: 'Payments',
    documents: 'Documents',
    activity: 'Activity',
    paymentHistory: 'View all your payment history',
    taxOrders: 'See all of your tax orders',
    uploadedFiles: 'Manage your uploaded files',
    infoSupport: 'Info & Support',
    aboutUs: 'About Us',
    aboutUsDesc: 'Learn more about Smart Tax BD',
    contactUs: 'Contact Us',
    contactUsDesc: 'Get in touch with our support team',
    account: 'Account',
    signOut: 'Sign out',
    signOutConfirm: 'Are you sure you want to sign out?',
    deleteAccount: 'Delete account',
    deleteAccountDesc:
      "This action is permanent and can't be undone. All your data will be removed.",
    deleteConfirm: 'Delete',
    notSignedIn: "You're not signed in",
    notSignedInDesc: 'Sign in to sync your data, save drafts, and manage tax info.',
    signIn: 'Sign In',
    createAccount: 'Create Account',
    role: 'Role',
    location: 'Location',
    locationNA: 'Not available',
    myFiles: 'My Files',
    myFilesDesc: 'Your all files',
    language: 'Language',
    theme: 'Theme',
    dark: 'Dark',
    light: 'Light',
    version: 'Version 1.0.0',
  },
  common: {
    yes: 'Yes',
    no: 'No',
    cancel: 'Cancel',
    see_all: 'See All',
    view_all: 'View All',
    not_available: 'N/A',
    note: 'Note:',
    featured: 'Featured',
    from: 'From:',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    tax: 'Tax',
    total: 'Total',
    free: 'FREE',
    change: 'Change',
    add: 'Add',
    done: 'Done',
    loading: 'Please wait...',
    noDataTitle: 'No data available',
    noDataMessage: 'Try again later or adjust your filters.',
    docDefault: 'Document',
    fileUploaded: 'File uploaded',
    noFileYet: 'No file yet',
    tapToReplace: 'Tap to replace',
    tapToUpload: 'Tap to upload',
    view: 'View',
    missing: 'Missing',
    preview: 'Preview',
    previewImage: 'Preview the image below',
    previewPdf: 'PDF document',
    previewOther: 'Download to view this file',
    pdfNotSupported: 'PDF preview is not supported in-app.',
    openPdfBrowser: 'Open PDF in Browser',
    previewNotAvailable: 'Preview not available.\nDownload to view.',
    close: 'Close',
    download: 'Download',
    downloading: 'Downloading…',
    popular: 'POPULAR',
    recommended: 'RECOMMENDED',
    contactForPricing: 'Contact for pricing',
    showFeatures: 'Show features',
    hideFeatures: 'Hide features',
    tabHome: 'Home',
    tabNews: 'News',
    tabFiling: 'Filing',
    tabBlogs: 'Blogs',
    tabFaq: 'FAQ',
    tabProfile: 'Profile',
  },
  order: {
    successTitle: 'Order Placed Successfully!',
    successDescription:
      'Your tax order has been placed. The authority will contact you for bKash payment.',
    goHome: 'Go to Home',
    goOrders: 'Go to Orders',
  },
  payment: {
    noOrderSelected: 'No order selected.',
    createOrder: 'Create Order',
    failedToLoad: 'Failed to load order payment status.',
    retry: 'Retry',
    step3Title: 'Step 3: Payment',
    step3Description: 'Complete payment to place your tax order.',
    cardTitle: 'Order Payment Status',
    orderStatus: 'Order Status',
    currentStep: 'Current Step',
    fee: 'Fee',
    paymentSuccessful: 'Payment successful. Order placed.',
    paymentPending: 'Payment pending.',
    startPayment: 'Start Payment',
    refreshStatus: 'Refresh Status',
    backToStep2: 'Back to Step 2',
    bkashModalTitle: 'bKash Payment',
    bkashModalDescription:
      'We are currently working on the bKash payment system, so automatic online payment is not yet available. For now, the authority will contact you directly to complete your bKash payment. Press OK to place the order, we will contact you for payment.',
    cancel: 'Cancel',
    ok: 'OK',
  },
  auth: {
    signInTitle: 'Sign In',
    signUpTitle: 'Create Account',
    forgotPasswordTitle: 'Forgot Password?',
    verifyOtpTitle: 'Verify OTP',
    welcomeBack: 'Welcome Back',
    welcomeBackDesc: 'Log in to manage your tax filings',
    createAccountDesc: 'Get started with Smart Tax BD',
    mobilePlaceholder: 'Enter your mobile number...',
    mobileHint: 'e.g. 018',
    mobileHintFull: 'e.g. 01712345678',
    fullNameLabel: 'Full Name',
    fullNameHint: 'e.g. Rahim Hasan',
    emailLabel: 'Email Address',
    emailHint: 'e.g. rahim@email.com',
    passwordLabel: 'Password',
    confirmPasswordLabel: 'Confirm Password',
    newPasswordLabel: 'New Password',
    termsConsent:
      'By creating an account you agree to our Terms of Service and Privacy Policy.',
    alreadyHaveAccount: 'Already have an account?',
    rememberedIt: 'Remembered it?',
    verificationCodeTitle: 'Enter Verification Code',
    verificationCodeLabel: 'Verification Code',
    verificationCodeDesc: 'We sent a 6-digit code to',
    didNotGetCode: "Didn't get a code?",
    verifyCodeButton: 'Verify Code',
    resetPasswordTitle: 'Set New Password',
    resetPasswordDesc: 'Choose a new password for your account.',
    resetPasswordButton: 'Reset Password',
    passwordResetSuccess: 'Password reset successfully. Please log in.',
    passwordPlaceholder: 'Password *',
    fullNamePlaceholder: 'Full Name *',
    emailPlaceholder: 'Email Address',
    confirmPasswordPlaceholder: 'Confirm Password *',
    rememberMe: 'Remember me',
    forgotPasswordLink: 'Forgot password?',
    signInButton: 'Log In',
    signingIn: 'Signing...',
    signUpLink: "Don't have an account?",
    signUpLinkAction: 'Create Account',
    termsAndConditions: 'I agree to the Terms of Service and Privacy Policy',
    createAccountButton: 'Create Account',
    softwareSlogan: '#1 Tax Software in Bangladesh',
    createAccountSlogan: "Let's Create your Smart Tax BD account",
    madeIn: 'Made in',
    copyright:
      'Mobile App is developed by Smart Tax BD Technology Ltd. smarttaxbd.com.bd is copyrighted by Bangladesh Copyright and Patent office. Copyright registration number is 14748-COPR.',
    forgotPasswordDesc:
      "Enter the mobile number linked to your account and we'll send a OTP.",
    mobileLabel: 'Mobile Number',
    sendOtpButton: 'Send OTP',
    rememberPassword: 'Remember your password?',
    verifyOtpDesc: "We've sent a 6-digit verification code to",
    mobileNumberDefault: 'your mobile number',
    resendCodeIn: 'Resend code in',
    didNotReceiveCode: "Didn't receive the code?",
    resend: 'Resend',
    verifyOtpButton: 'Verify OTP',
    verifyOtpHelp: 'Enter the 6-digit code sent to your mobile number to continue.',
    nameMin: 'Name must be at least 2 characters',
    emailRequired: 'Email is required',
    emailInvalid: 'Invalid email address',
    mobileMin: 'Phone number must be at least 11 characters',
    mobileInvalid: 'Enter a valid mobile number (e.g. 01712345678)',
    passwordMin: 'Password must be at least 6 characters',
    termsRequired: 'You must accept the terms and conditions',
    passwordsMismatch: 'Passwords do not match',
    otpSent: 'OTP sent to your mobile number',
    otpVerified: 'Account verified successfully',
    verifyFail: 'Failed to verify OTP. Please try again.',
    mobileMissing: 'Mobile number is missing. Please try again.',
    resendFail: 'Failed to resend OTP. Please try again.',
  },
};
