export default {
  home: {
    headerTitle: 'Home',
    newsSection: 'Latest News',
    taxTypes: 'Services',
    loading: 'Loading tax types...',
    error: 'Failed to load tax categories',
    notFound: 'No tax categories found',
  },
  profile: {
    headerTitle: 'Profile',
    headerDescription: 'Manage your account and preferences',
    overview: 'Overview',
    orders: 'Orders',
    payments: 'Payments',
    documents: 'Documents',
    activity: 'Activity',
    paymentHistory: 'View all your payment history',
    taxOrders: 'See all of your tax orders',
    uploadedFiles: 'Manage your uploaded files',
    infoSupport: 'Info & Support',
    aboutUs: 'About Us',
    aboutUsDesc: 'Learn more about Smart Tax BD',
    contactUs: 'Contact Us',
    contactUsDesc: 'Get in touch with our support team',
    account: 'Account',
    signOut: 'Sign out',
    signOutConfirm: 'Are you sure you want to sign out?',
    deleteAccount: 'Delete account',
    deleteAccountDesc:
      "This action is permanent and can't be undone. All your data will be removed.",
    deleteConfirm: 'Delete',
    notSignedIn: "You're not signed in",
    notSignedInDesc: 'Sign in to sync your data, save drafts, and manage tax info.',
    signIn: 'Sign In',
    createAccount: 'Create Account',
    role: 'Role',
    location: 'Location',
    locationNA: 'Not available',
  },
  common: {
    yes: 'Yes',
    no: 'No',
    cancel: 'Cancel',
    see_all: 'See All',
    view_all: 'View All',
    not_available: 'N/A',
    note: 'Note:',
    featured: 'Featured',
    from: 'From:',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    tax: 'Tax',
    total: 'Total',
    free: 'FREE',
    change: 'Change',
    add: 'Add',
    done: 'Done',
    loading: 'Please wait...',
  },
};
